// Generated by scripts/package-custom-helper-extension.mjs for partner builds.
export const PARTNER_CONFIG = Object.freeze({
  controlPlaneOrigin: 'https://magic-city.ai',
  launchOrigins: Object.freeze(['https://example.com']),
  helperPluginId: 'acme-reading-helper',
  helperOwnerAgentId: 'acme-reading-agent',
  extensionName: 'Acme Magic City Helper',
  optionalMerchantOrigins: Object.freeze(['https://example.com/*']),
  profile: 'release'
});
